create table if not exists public.skills (
  id text primary key,
  job_id text not null,
  job_tier text not null check (job_tier in ('basic', 'first', 'second', 'advancedSecond')),
  name text not null,
  icon_url text,
  max_level integer not null,
  body_lv1 text not null,
  body_lvmax text not null,
  cast_time_lv1 text not null,
  cast_time_lvmax text not null,
  cooldown_lv1 text not null,
  cooldown_lvmax text not null,
  sp_cost_lv1 text not null,
  sp_cost_lvmax text not null,
  global_delay_lv1 text not null,
  global_delay_lvmax text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.skill_tags (
  id bigint generated by default as identity primary key,
  skill_id text not null references public.skills(id) on delete cascade,
  tag text not null,
  sort_order integer not null default 0
);

create table if not exists public.skill_diff_stats (
  id bigint generated by default as identity primary key,
  skill_id text not null references public.skills(id) on delete cascade,
  label text not null,
  from_value text not null,
  to_value text not null,
  sort_order integer not null default 0
);

create index if not exists skills_job_id_sort_order_idx on public.skills (job_id, sort_order);
create index if not exists skill_tags_skill_id_sort_order_idx on public.skill_tags (skill_id, sort_order);
create index if not exists skill_diff_stats_skill_id_sort_order_idx on public.skill_diff_stats (skill_id, sort_order);

alter table public.skills enable row level security;
alter table public.skill_tags enable row level security;
alter table public.skill_diff_stats enable row level security;

drop policy if exists "skills_public_read" on public.skills;
create policy "skills_public_read"
  on public.skills
  for select
  to anon, authenticated
  using (true);

drop policy if exists "skill_tags_public_read" on public.skill_tags;
create policy "skill_tags_public_read"
  on public.skill_tags
  for select
  to anon, authenticated
  using (true);

drop policy if exists "skill_diff_stats_public_read" on public.skill_diff_stats;
create policy "skill_diff_stats_public_read"
  on public.skill_diff_stats
  for select
  to anon, authenticated
  using (true);
