create extension if not exists pg_trgm;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.build_equipment_search_text(
  p_item_name_jp_display text,
  p_item_name_jp_raw text,
  p_item_name_en text,
  p_equip_slot text,
  p_genre_bucket text,
  p_level integer,
  p_battle_power integer,
  p_equipment_score integer,
  p_card_slots integer,
  p_status_text_core text,
  p_tag_tokens text[] default '{}'::text[],
  p_genre_tokens text[] default '{}'::text[]
)
returns text
language sql
immutable
as $$
  select trim(
    regexp_replace(
      replace(
        concat_ws(
          ' ',
          coalesce(p_item_name_jp_display, ''),
          coalesce(p_item_name_jp_raw, ''),
          coalesce(p_item_name_en, ''),
          coalesce(p_equip_slot, ''),
          coalesce(p_genre_bucket, ''),
          coalesce(p_level::text, ''),
          coalesce(p_battle_power::text, ''),
          coalesce(p_equipment_score::text, ''),
          coalesce(p_card_slots::text, ''),
          coalesce(p_status_text_core, ''),
          array_to_string(coalesce(p_tag_tokens, '{}'::text[]), ' '),
          array_to_string(coalesce(p_genre_tokens, '{}'::text[]), ' ')
        ),
        E'\n',
        ' '
      ),
      '\s+',
      ' ',
      'g'
    )
  );
$$;

create or replace function public.build_equipment_genre_search_text(
  p_genre_name_jp text,
  p_genre_bucket text,
  p_genre_attribute_text text,
  p_genre_set_effect_text text
)
returns text
language sql
immutable
as $$
  select trim(
    regexp_replace(
      replace(
        concat_ws(
          ' ',
          coalesce(p_genre_name_jp, ''),
          coalesce(p_genre_bucket, ''),
          coalesce(p_genre_attribute_text, ''),
          coalesce(p_genre_set_effect_text, '')
        ),
        E'\n',
        ' '
      ),
      '\s+',
      ' ',
      'g'
    )
  );
$$;

create table if not exists public.equipment_items (
  id text primary key,
  item_name_jp_display text not null,
  item_name_jp_raw text,
  item_name_en text,
  equip_slot text not null check (
    equip_slot in (
      'メインウェポン',
      'サブウェポン',
      '防具',
      '肩にかける物',
      '靴',
      'アクセサリー',
      '頭装備',
      '顔飾り',
      '口飾り',
      '背中装備',
      '衣装'
    )
  ),
  genre_bucket text not null check (genre_bucket in ('main_weapon', 'sub_weapon', 'armor_set', 'accessory', 'other')),
  level integer not null,
  battle_power integer,
  equipment_score integer,
  card_slots integer check (card_slots is null or card_slots >= 0),
  status_text_core text not null,
  search_text text not null default '',
  icon_url text,
  artwork_url text,
  sort_order integer not null default 0,
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.equipment_items.item_name_jp_display is
  'Normalized display name. Accessory slot suffixes like [2] should be removed from this column.';
comment on column public.equipment_items.status_text_core is
  'Only the equipment status core lines. Descriptive help text from the UI must not be stored here.';

create table if not exists public.equipment_genres (
  id bigint generated by default as identity primary key,
  genre_name_jp text not null unique,
  genre_bucket text not null check (genre_bucket in ('main_weapon', 'sub_weapon', 'armor_set', 'accessory', 'other')),
  genre_attribute_text text not null default '',
  genre_set_effect_text text not null default '',
  search_text text not null default '',
  sort_order integer not null default 0,
  status text not null default 'published' check (status in ('draft', 'published', 'archived'))
);

create table if not exists public.equipment_genre_members (
  equipment_id text not null references public.equipment_items(id) on delete cascade,
  genre_id bigint not null references public.equipment_genres(id) on delete cascade,
  primary key (equipment_id, genre_id)
);

create table if not exists public.equipment_tags (
  id bigint generated by default as identity primary key,
  tag_key text not null unique,
  tag_label text not null,
  tag_group text not null,
  sort_order integer not null default 0
);

create table if not exists public.equipment_item_tags (
  equipment_id text not null references public.equipment_items(id) on delete cascade,
  tag_id bigint not null references public.equipment_tags(id) on delete cascade,
  primary key (equipment_id, tag_id)
);

create index if not exists equipment_items_status_sort_order_idx on public.equipment_items (status, sort_order);
create index if not exists equipment_items_equip_slot_idx on public.equipment_items (equip_slot);
create index if not exists equipment_items_genre_bucket_idx on public.equipment_items (genre_bucket);
create index if not exists equipment_items_level_idx on public.equipment_items (level);
create index if not exists equipment_items_search_text_trgm_idx on public.equipment_items using gin (search_text gin_trgm_ops);
create index if not exists equipment_genres_bucket_status_idx on public.equipment_genres (genre_bucket, status, sort_order);
create index if not exists equipment_genres_search_text_trgm_idx on public.equipment_genres using gin (search_text gin_trgm_ops);
create index if not exists equipment_genre_members_genre_id_equipment_id_idx on public.equipment_genre_members (genre_id, equipment_id);
create index if not exists equipment_item_tags_tag_id_equipment_id_idx on public.equipment_item_tags (tag_id, equipment_id);
create index if not exists equipment_tags_group_sort_order_idx on public.equipment_tags (tag_group, sort_order);

drop trigger if exists set_equipment_items_updated_at on public.equipment_items;
create trigger set_equipment_items_updated_at
before update on public.equipment_items
for each row
execute function public.set_updated_at();

alter table public.equipment_items enable row level security;
alter table public.equipment_genres enable row level security;
alter table public.equipment_genre_members enable row level security;
alter table public.equipment_tags enable row level security;
alter table public.equipment_item_tags enable row level security;

drop policy if exists "equipment_items_public_read" on public.equipment_items;
create policy "equipment_items_public_read"
  on public.equipment_items
  for select
  to anon, authenticated
  using (true);

drop policy if exists "equipment_genres_public_read" on public.equipment_genres;
create policy "equipment_genres_public_read"
  on public.equipment_genres
  for select
  to anon, authenticated
  using (true);

drop policy if exists "equipment_genre_members_public_read" on public.equipment_genre_members;
create policy "equipment_genre_members_public_read"
  on public.equipment_genre_members
  for select
  to anon, authenticated
  using (true);

drop policy if exists "equipment_tags_public_read" on public.equipment_tags;
create policy "equipment_tags_public_read"
  on public.equipment_tags
  for select
  to anon, authenticated
  using (true);

drop policy if exists "equipment_item_tags_public_read" on public.equipment_item_tags;
create policy "equipment_item_tags_public_read"
  on public.equipment_item_tags
  for select
  to anon, authenticated
  using (true);
