create extension if not exists pg_trgm;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.build_card_search_text(
  p_card_name_jp text,
  p_card_name_en text,
  p_rarity text,
  p_equip_slot text,
  p_level_band text,
  p_card_type text,
  p_effect_text_base text,
  p_effect_text_evolution text,
  p_effect_text_storage text,
  p_tag_tokens text[] default '{}'::text[],
  p_category_tokens text[] default '{}'::text[]
)
returns text
language sql
immutable
as $$
  select trim(
    regexp_replace(
      replace(
        concat_ws(
          ' ',
          coalesce(p_card_name_jp, ''),
          coalesce(p_card_name_en, ''),
          coalesce(p_rarity, ''),
          coalesce(p_equip_slot, ''),
          coalesce(p_level_band, ''),
          coalesce(p_card_type, ''),
          coalesce(p_effect_text_base, ''),
          coalesce(p_effect_text_evolution, ''),
          coalesce(p_effect_text_storage, ''),
          array_to_string(coalesce(p_tag_tokens, '{}'::text[]), ' '),
          array_to_string(coalesce(p_category_tokens, '{}'::text[]), ' ')
        ),
        E'\n',
        ' '
      ),
      '\s+',
      ' ',
      'g'
    )
  );
$$;

create table if not exists public.cards (
  id text primary key,
  card_name_jp text not null,
  card_name_en text,
  rarity text not null check (rarity in ('緑カード', '青カード', '紫カード', '橙カード', '赤カード')),
  equip_slot text not null check (
    equip_slot in (
      'メインウェポン',
      'サブウェポン',
      '防具',
      '肩にかける物',
      '靴',
      'アクセサリー',
      '頭装備',
      '顔飾り',
      '口飾り',
      '背中装備',
      '衣装'
    )
  ),
  level_band text not null,
  card_type text not null,
  icon_url text,
  artwork_url text,
  sort_order integer not null default 0,
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  effect_text_base text not null,
  effect_text_evolution text,
  effect_text_storage text,
  search_text text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.cards.effect_text_evolution is
  'Temporary aggregated evolution text. TODO: split into structured stage data such as lv5/lv10/lv15 when stage-aware filtering is needed.';
comment on column public.cards.effect_text_storage is
  'Collection/storage effect text shown separately from base/evolution effects.';

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  tag_key text not null unique,
  tag_label text not null,
  tag_group text not null,
  sort_order integer not null default 0
);

create table if not exists public.card_tags (
  card_id text not null references public.cards(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (card_id, tag_id)
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  category_key text not null unique,
  category_label text not null,
  sort_order integer not null default 0
);

create table if not exists public.card_categories (
  card_id text not null references public.cards(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  primary key (card_id, category_id)
);

create index if not exists cards_status_sort_order_idx on public.cards (status, sort_order);
create index if not exists cards_rarity_idx on public.cards (rarity);
create index if not exists cards_equip_slot_idx on public.cards (equip_slot);
create index if not exists cards_level_band_idx on public.cards (level_band);
create index if not exists cards_card_type_idx on public.cards (card_type);
create index if not exists cards_search_text_trgm_idx on public.cards using gin (search_text gin_trgm_ops);
create index if not exists card_tags_tag_id_card_id_idx on public.card_tags (tag_id, card_id);
create index if not exists card_categories_category_id_card_id_idx on public.card_categories (category_id, card_id);
create index if not exists tags_tag_group_sort_order_idx on public.tags (tag_group, sort_order);
create index if not exists categories_sort_order_idx on public.categories (sort_order);

drop trigger if exists set_cards_updated_at on public.cards;
create trigger set_cards_updated_at
before update on public.cards
for each row
execute function public.set_updated_at();

alter table public.cards enable row level security;
alter table public.tags enable row level security;
alter table public.card_tags enable row level security;
alter table public.categories enable row level security;
alter table public.card_categories enable row level security;

drop policy if exists "cards_public_read" on public.cards;
create policy "cards_public_read"
  on public.cards
  for select
  to anon, authenticated
  using (true);

drop policy if exists "tags_public_read" on public.tags;
create policy "tags_public_read"
  on public.tags
  for select
  to anon, authenticated
  using (true);

drop policy if exists "card_tags_public_read" on public.card_tags;
create policy "card_tags_public_read"
  on public.card_tags
  for select
  to anon, authenticated
  using (true);

drop policy if exists "categories_public_read" on public.categories;
create policy "categories_public_read"
  on public.categories
  for select
  to anon, authenticated
  using (true);

drop policy if exists "card_categories_public_read" on public.card_categories;
create policy "card_categories_public_read"
  on public.card_categories
  for select
  to anon, authenticated
  using (true);
